title: Petra Stojičić
description: description
baseurl: "/cv-petra-00"
url: "https://petrusina.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Personal info
author:
  name: Petra Stojičić
  title: Your Professional Title
  email: pet.stojicic@gmail.com
  phone: +385 99 2502 411
  location: Aarhus, Denmark
  website: https://petrusina.github.io/cv-petra-00

# Navigation
navigation:
  - title: About
    url: /about
  - title: Experience
    url: /experience
  - title: Projects
    url: /projects
  - title: Skills
    url: /skills
  - title: Contact
    url: /contact

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
